name: Node CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE: test
      DB_USER: root
      DB_PASSWORD: "root"
      DB_HOST: localhost
      DB_DIALECT: "mysql"
      PORT: "3000"
      NODE_ENV: "development"

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x, 16.x]
    steps:
      - run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE test;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - name: Cancel previous runs of this workflow
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - name: npm install and test
        run: |
          npm install
          npm run start &
          npm run mochaClient

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/master'
  #   steps:
  #   - name: executing remote ssh commands using password
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       password: ${{ secrets.PASSWORD }}
  #       key: ${{ secrets.KEY }}
  #       script: ./deploy.sh
